POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name": "John Chena",
    "username": "customer",
    "email": "john.chena@example.com",
    "phone": "08954479582",
    "password": "password123",
    "confirmPassword": "password123",
    "address": "Serang",
    "role": "customer"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "identifier": "employee",
    "password": "password123"
}

###
GET http://localhost:8080/api/v1/user
Authorization: Bearer <your-access-token-here>


###
GET http://localhost:8080/api/v1/user/129c3c57-ce14-4bab-ae11-c2721703890c
Authorization: Bearer <your-access-token-here>


###
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
    "refreshToken": "<your-refresh-token-here>
"
}

###
POST http://localhost:8080/api/v1/auth/logout
Authorization: Bearer <your-access-token-here>

Content-Type: application/json

{
    "refreshToken": "<your-refresh-token-here>
"
}


###
POST http://localhost:8080/api/v1/product/
Authorization: Bearer <your-access-token-here>

Content-Type: application/json

{
    "name": "Beras",
    "description": "Beras pulen Indramayu",
    "price": 230000,
    "unit": "karung"
}

###
GET http://localhost:8080/api/v1/product/

###
PUT http://localhost:8080/api/v1/product/314da5a1-4fe6-440b-a531-6adc9d65ec59
Authorization: Bearer <your-access-token-here>

Content-Type: application/json

{
    "name": "Semangka",
    "description": "Product 1 description",
    "price": 9000,
    "unit": "kg"
}

###
POST http://localhost:8080/api/v1/transaction/
Authorization: Bearer <your-access-token-here>

Content-Type: application/json

{
    "transaction": {
        "customerId": "129c3c57-ce14-4bab-ae11-c2721703890c",
        "notes": "Catatan transaksi"
    },
    "details": [
        {
        "productId": "54b4ee92-3d74-4969-80a8-1c9a2cd1ff20",
        "productPrice": 230000,
        "qty": 2,
        "discountAmount": 10000,
        "notes": "Beras pulen Indramayu"
        },
        {
        "productId": "314da5a1-4fe6-440b-a531-6adc9d65ec59",
        "productPrice": 9000,
        "qty": 1,
        "discountAmount": 0,
        "notes": "Semangka Manis"
        }
    ]
}